# Generated by Django 5.0.4 on 2024-06-02 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="order.cart",
                verbose_name="Cart",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customer",
            ),
        ),
    ]
