# Generated by Django 4.2.3 on 2023-07-09 16:23

import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models

import demo.product.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "kind",
                    django_choices_field.fields.TextChoicesField(
                        choices=[("physical", "Physical"), ("virtual", "Virtual")],
                        choices_enum=demo.product.models.Product.Kind,
                        default="physical",
                        max_length=8,
                        verbose_name="Category",
                    ),
                ),
                ("description", models.TextField(default="", verbose_name="Description")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=24, verbose_name="Price"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="images",
                        to="product.brand",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(max_length=2000, upload_to="", verbose_name="Image")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="images",
                        to="product.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
    ]
