# Generated by Django 5.0.4 on 2024-06-02 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_brand_alter_productimage_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="product.brand",
                verbose_name="Brand",
            ),
        ),
    ]
